apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: appguestbook
spec:
  generators:
  - list:
      elements:
      - cluster: in-local
        url: https://kubernetes.default.svc
      - cluster: prueba2
        url: https://prueba2-dns-ndjbure8.hcp.westeurope.azmk8s.io
  template:
    metadata:
      name: '{{cluster}}-guestbook'
      namespace: appguestbook
    spec:
      project: default
      source:
        repoURL: https://github.com/tomascasillas1/argocd.git
        targetRevision: main
        path: appguestbook
      destination:
        server: '{{url}}'
        namespace: appguestbook
      syncPolicy:
         syncOptions:
          - CreateNamespace=true
