---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: apache
spec:
  type: LoadBalancer
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31288
