apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-pro
  namespace: apps
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/tomascasillas1/argocd.git
          revision: main
          directories:
          - path: apps-pro/*
      - clusters:
          selector:
            matchLabels:
              entorno: "pro"
  template:
    metadata:
      name: '{{ nameNormalized }}-{{path.basename}}'
      namespace: apps
    spec:
      project: iniciales
      source:
        repoURL: https://github.com/tomascasillas1/argocd.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{ nameNormalized }}-{{path.basename}}'
      syncPolicy:
         syncOptions:
          - CreateNamespace=true