---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: httpd:latest
          name: httpd
          ports:
            - containerPort: 80
