---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appguestbook
  namespace: argocd
spec:
  destination:
    namespace: appguestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: appguestbook
    repoURL: https://github.com/tomascasillas1/argocd.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
